AllCops:
  TargetRubyVersion: 2.3

# This is fine, really
Style/FileName:
  Enabled: false

# 'old' style
Style/EmptyMethod:
  EnforcedStyle: expanded

# It makes much more sense to group them according to purpose
Bundler/OrderedGems:
  Enabled: false

# Not interchangeable
Style/ModuleFunction:
  Enabled: false

# Doesn't really matter
Style/FrozenStringLiteralComment:
  Enabled: false

# Doesn't really make sense for multiline
Style/TrailingCommaInLiteral:
  Enabled: false

# Tests should be as long as they need to be
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
