AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  NewCops: disable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

# 'old' style
Style/EmptyMethod:
  EnforcedStyle: expanded

# It makes much more sense to group them according to purpose
Bundler/OrderedGems:
  Enabled: false

# `module_function` and `extend self` aren't actually interchangeable
Style/ModuleFunction:
  Enabled: false

# Doesn't really matter
Style/FrozenStringLiteralComment:
  Enabled: false

# Doesn't really make sense for multiline
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Tests should be as long as they need to be
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
